api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: code_runner

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: default
        domain:
          main: "localhost"
