from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field, model_validator


class PersonaType(StrEnum):
    PLANNER = "planner"
    IMPLEMENTOR = "implementor"
    REVIEWER = "reviewer"
    QA_REVIEWER = "qa-reviewer"
    TECH_LEAD = "tech-lead"


StageExecutorOverride = Literal["ai", "engine"]


class PersonaEntry(BaseModel):
    """A single persona instantiation: type x speciality."""

    type: PersonaType
    speciality: str | None = None

    @property
    def key(self) -> str:
        if self.speciality:
            return f"{self.type}×{self.speciality}"
        return str(self.type)


class StageOverride(BaseModel):
    """Override the default executor for a specific stage."""

    stage: str
    executor: StageExecutorOverride


class RoutingRule(BaseModel):
    """Map a persona to specific repos or roles."""

    persona: str
    repos: list[str] = Field(default_factory=list)
    role: str = ""


class SkillOverrideEntry(BaseModel):
    """A project-specific skill override or addition."""

    id: str
    stage: str = ""
    executor: str = ""
    applies_to: str | list[str] = "neutral"
    specialities: list[str] = Field(default_factory=list)
    body: str = ""


class ExecutionProfile(BaseModel):
    """Spec §17.5 — the per-project execution profile.

    Generated by the tech-lead session (#23), not hand-edited. But a
    hand-written profile still loads and validates. Distinct from
    project.yaml (human-authored config) — different change cadence.
    """

    personas: list[PersonaEntry]
    stage_overrides: list[StageOverride] = Field(default_factory=list)
    routing: list[RoutingRule] = Field(default_factory=list)
    qa_specialities: list[str] = Field(default_factory=list)
    skill_overrides: list[SkillOverrideEntry] = Field(default_factory=list)

    @model_validator(mode="after")
    def _validate_personas_not_empty(self) -> ExecutionProfile:
        if not self.personas:
            raise ValueError("At least one persona must be declared")
        return self
